### ISSUE TITLE
Errors in paho.mqtt

### ISSUE THREAD

**Issue by kptkip** [ClassicDIY/PylonToMQTT#5]
When I start the script I get the following errors:

**Command**
python3 pylon_to_mqtt.py --pylon_port /dev/serial/by-id/usb-FTDI_FT232R_USB_UART_B0001B3W-if00-port0 --baud_rate 9600  --mqtt_host [MY_IP] --mqtt_port [;MY_PORT] --mqtt_root SmartHome/Jakiper

**Error message:**
Traceback (most recent call last):
  File "pylon_to_mqtt.py", line 1, in <module>
    from paho.mqtt import client as mqttclient, error_string
ImportError: cannot import name 'error_string' from 'paho.mqtt' (/home/pi/.local/lib/python3.7/site-packages/paho/mqtt/__init__.py)

**Comment by graham22** [comment]
Updated reference to paho.mqtt client error_string
